"""
This is the handler file for a single cloak experiment. Arguments are passed in via command line by running one of the
autoscripts generated by run_cloak_experiments.py. You do not need to interact with cloak.py on a normal run unless you wish to 
run a single manually created run instead of one of the autoscripts.
"""

from facenet_pytorch import MTCNN
import torch
import argparse
from cloaker import Cloaker
from cloak_functions import pgd_cloak, sgd_cloak, afog_cloak, afog_cloak_multi, pgd_cloak_multi
from loss_functions import fawkes_loss, triplet_loss, dssim_loss, lpips_loss, mse_loss, untarget_loss
from dist_functions import cosine_dist, l2_dist
from advcloak.model_irse import IR_50
from utils import preprocess_tanh, reverse_tanh, preprocess_divide, reverse_divide
from insightface_code.recognition.arcface_torch.backbones import get_model

parser = argparse.ArgumentParser()
parser.add_argument("--probe_dataset_path", type=str, help="Path to probe images")
parser.add_argument("--gallery_dataset_path", type=str, help="Path to gallery images")
parser.add_argument("--extractor_path", type=str, default=None, help="Path to extractor")
parser.add_argument("--batch_size", type=int, default=32, help="Batch Size")
parser.add_argument("--cropped_im_size", type=int, default=112, help="Crop size to apply MTCNN")
parser.add_argument("--num_dataset_images", type=float, default=1.0, help="Number of images to take from dataset")
parser.add_argument("--cloak_save_path", type=str, default="data/pubfig_cloaked", help="Path to save cloaked images")
parser.add_argument("--verbosity", type=str, default="none", help="Error verbosity level")
parser.add_argument("--extractor_type", type=str, default="Facenet", help="The model to use for extracting embeddings")
parser.add_argument("--distance_function", type=str, default="l2", help="Distance function to use when comparing embedding vectors")
parser.add_argument("--norm_function", type=str, default="tanh", help="Normalization function for preparing images")
parser.add_argument("--cloak_function", type=str, default="pgd_cloak", help="The optimization to use for cloaking images")
parser.add_argument("--multi_cloak_function", type=str, default="pgd_cloak", help="The optimization for using multi-cloak on the images")
parser.add_argument("--do_stickers", type=int, default=False, help="Whether to add region stickers to the perturbation optimization")
parser.add_argument("--do_highpass", type=int, default=False, help="Whether to add highpass to the perturbation optimization")
parser.add_argument("--cloak_loss", type=str, default="fawkes", help="The loss function to use for cloaking images.")
parser.add_argument("--multi_cloak_loss", type=str, default="fawkes", help="The loss function to use for multi-cloaking images.")
parser.add_argument("--cloak_function_iters", type=int, default=10, help="Number of iterations to run the optimization")
parser.add_argument("--multi_cloak_function_iters", type=int, default=10, help="Number of iterations for multi-cloak optimization")
parser.add_argument("--cloak_function_step", type=float, default=1., help="Step size for optimization methods with step sizes")
parser.add_argument("--cloak_function_max_pert", type=float, default=1., help="Maximum perturbation for optimization methods with max perturbations")
parser.add_argument("--multi_cloak_function_max_pert", type=float, default=1., help="Maximum perturbation for multicloak pretraining")
parser.add_argument("--cloak_function_lr", type=float, default=0.5, help="Learning rate for optimization methods with learning rates")
parser.add_argument("--cloak_percep_loss", type=str, default="none", help="Perceptual loss to use in loss calculation. If none, only clipping will be used")
parser.add_argument("--percep_loss_weight", type=str, default=0.0, help="Weighted factor for adding perceptual loss to cloak loss")
parser.add_argument("--mode", type=str, default="perturb", help="Whether to use perturb mode, multi mode, or makeup mode")
parser.add_argument("--makeup_mode", type=str, default="diffam", help="Which makeup method to use, either diffam or amt-gan")
parser.add_argument("--gen_save_path", type=str, default="/", help="Path to save generated images, if using")
parser.add_argument("--num_gen_iterations", type=int, default=5, help="Gen iterations if using")
parser.add_argument("--gen_learning_rate", type=float, default=0.1, help="Default learning rate for generating images")
parser.add_argument("--num_images_to_gen", type=int, default=4)
parser.add_argument("--use_real", type=int, default=0, help="Whether to use real images for training instead of synthetic if they're available")
parser.add_argument("--n_to_eval", type=int, default=1, help="Top-n to images to eval over")
args = parser.parse_args()

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

# Be sure that the mode aligns with the cloak function selected
if args.mode == "multi":
      assert args.multi_cloak_function in ["pgd_cloak_multi", "afog_cloak_multi", "pgd_cloak_sticker", "afog_cloak_sticker"], "Multi mode is only compatible with multi cloak functions."

args.cloak_function_step = args.cloak_function_step / 255.
args.cloak_function_max_pert = args.cloak_function_max_pert / 255.
args.multi_cloak_function_max_pert = args.multi_cloak_function_max_pert / 255.

# Below are all of the possible cloak functions, cloak losses, distance functions, normalization functions, and perceptual losses
cloak_funcs = {
        "pgd_cloak":pgd_cloak,
        "pgd_cloak_multi":pgd_cloak_multi,
        "sgd_cloak":sgd_cloak,
        "afog_cloak":afog_cloak,
        "afog_cloak_multi":afog_cloak_multi,
        "none":None
    }

cloak_losses = {
        "fawkes":fawkes_loss,
        "triplet":triplet_loss,
        "untarget":untarget_loss,
        "none":None
    }

distance_funcs = {
        "cosine":cosine_dist,
        "l2":l2_dist
    }

norm_funcs = {
        "tanh":preprocess_tanh,
        "divide":preprocess_divide
        }

reverse_norm_funcs = {
        "tanh":reverse_tanh,
        "divide":reverse_divide
        }

percep_losses = {
        "dssim": dssim_loss,
        "lpips": lpips_loss,
        "mse": mse_loss,
        "none": None
        }

# Select which type of each we'll be using
cloak_function = cloak_funcs[args.cloak_function]
multi_cloak_function = cloak_funcs[args.multi_cloak_function]
loss_function = cloak_losses[args.cloak_loss]
multi_loss_function = cloak_losses[args.multi_cloak_loss]
distance_function = distance_funcs[args.distance_function]
norm_function = norm_funcs[args.norm_function]
reverse_norm_function = reverse_norm_funcs[args.norm_function]
percep_loss_function = percep_losses[args.cloak_percep_loss]


# Get MTCNN for crop, align, and landmarks
mtcnn = MTCNN(image_size=args.cropped_im_size, device=device).to(device)

print("Extracting with model:", args.extractor_type)

# Initialize cloaker
cloaker = Cloaker(
        probe_dataset_path=args.probe_dataset_path, 
        gallery_dataset_path=args.gallery_dataset_path,
        extractor=args.extractor_type,
        cropper=mtcnn, 
        batch_size=args.batch_size, 
        cropped_im_size=args.cropped_im_size, 
        device=device, 
        verbosity=args.verbosity,
        distance_function=distance_function,
        cloak_function=cloak_function,
        multi_cloak_function = multi_cloak_function,
        do_stickers = int(args.do_stickers) == 1,
        do_highpass = int(args.do_highpass) == 1,
        cloak_loss=loss_function,
        multi_cloak_loss=multi_loss_function,
        cloak_function_iters=args.cloak_function_iters,
        multi_cloak_function_iters=args.multi_cloak_function_iters,
        cloak_function_step=args.cloak_function_step,
        cloak_function_max_pert=args.cloak_function_max_pert,
        multi_cloak_function_max_pert=args.multi_cloak_function_max_pert,
        cloak_function_lr=args.cloak_function_lr,
        loss_func_select=args.cloak_loss,
        multi_loss_func_select=args.multi_cloak_loss,
        norm_function = norm_function,
        reverse_norm_function = reverse_norm_function,
        percep_loss = percep_loss_function,
        percep_loss_weight = args.percep_loss_weight,
        num_gen_iterations = args.num_gen_iterations,
        gen_learning_rate = args.gen_learning_rate,
        num_images_to_generate=args.num_images_to_gen,
        n_to_eval=args.n_to_eval,
        use_real= int(args.use_real) == 1,
        mode=args.mode,
        )

# Optional: If we only want to cloak a subset of paths, put them here and pass do_paths=paths for the cloak function
paths = [
        "data/privacy_celeb/probe/467440_14832175.jpg",
        "data/privacy_celeb/probe/498299_15809804.jpg",
        "data/privacy_celeb/train/296813_9413123.jpg",
        "data/privacy_celeb/train/157494_4995450.jpg",
        "data/privacy_celeb/train/619592_19655786.jpg",
        "data/privacy_celeb/train/211164_6710801.jpg"
        ]


# Cloak the images, passing in paths of specific images if desired
cloaker.cloak_all_multi(save_dir = args.cloak_save_path, gen_save_path = args.gen_save_path)#, do_paths=paths)
